version: "3.9"

services:

  web_arqueo:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web_arqueo
    ports:
      - "4321:4321"
    networks:
      - red-gane-int
    depends_on:
      - arqueo-server

  arqueo-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: arqueo-server
    ports:
      - "3000:3000"
    networks:
      - red-gane-int

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./well-known:/usr/share/nginx/html/.well-known
    depends_on:
      - web_arqueo
      - arqueo-server
    networks:
      - red-gane-int

networks:
  red-gane-int:
    external: true
