version: "3.8"

services:
  # --- Backend API principal
  api_arqueo:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: arqueo-server-1
    image: arqueo-server
    networks:
      - red-gane-int
    env_file:
      - ./server/.env

  # --- Frontend Astro SSR (Node)
  web-arqueo:
    image: nginx:stable-alpine3.19-slim
    container_name: web_arqueo
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_arqueo
    ports:
      - "3757:3757"
    networks:
      - red-gane-int

networks:
  red-gane-int:
    external: true