version: "3.8"

services:
  api_arqueo:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: arqueo-server-1
    image: arqueo-server
    networks:
      - red-gane-int
    restart: always

  astro_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: astro_app
    image: astro-server
    expose:
      - "4321"
    depends_on:
      - api_arqueo
    networks:
      - red-gane-int
    restart: always

  web-arqueo:
    image: nginx:stable-alpine3.19-slim
    container_name: web_arqueo
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - astro_app
      - api_arqueo
    ports:
      - "3757:3757"
    networks:
      - red-gane-int
    restart: always

networks:
  red-gane-int:
    external: true
