version: "3.8"

services:
  # --- Backend API principal
  api_arqueo:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: arqueo-server
    image: arqueo-server
    networks:
      - red-gane-int

  # --- Frontend Astro SSR (Node)
  web_arqueo:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web_arqueo
    image: web-arqueo
    expose:
      - "4321"
    environment:
      PUBLIC_CLERK_PUBLISHABLE_KEY: "${PUBLIC_CLERK_PUBLISHABLE_KEY}"
      CLERK_SECRET_KEY: "${CLERK_SECRET_KEY}"
      API_URL: "https://arqueos.serviredgane.cloud/api"
    depends_on:
      - api_arqueo
    networks:
      - red-gane-int

  # --- Reverse Proxy Nginx
  proxy_nginx:
    image: nginx:stable-alpine3.19-slim
    container_name: nginx_proxy
    depends_on:
      - web_arqueo
      - api_arqueo
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3757:80"
    networks:
      - red-gane-int

networks:
  red-gane-int:
    external: true
