version: "3.7"

services:
  api_arqueo:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: arqueo-server-1
    image: arqueo-server
    networks:
      - red-gane-int

  astro_ssr:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: astro-ssr
    image: astro-ssr
    command: ["node", "./dist/server/entry.mjs"]
    environment:
      - PORT=3000
    expose:
      - "3000"
    networks:
      - red-gane-int
    depends_on:
      - api_arqueo

  web-arqueo:
    image: nginx:stable-alpine3.19-slim
    container_name: web_arqueo
    volumes:
      - ./client/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist/client:/usr/share/nginx/html/client:ro
    depends_on:
      - astro_ssr
    ports:
      - "3757:3757"
    networks:
      - red-gane-int

networks:
  red-gane-int:
    external: true
